language: java

addons:
  sonarcloud:
      organization: "dorinen-github"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=dorinen-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=71c2d383b553a14b1584d3d288ca453cea94e62f -Dsonar.projectKey=com.ipiecoles.java.java350:java340 -Dsonar.branch=master